# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brutal Dedication
email: admin@brutal-dedication.de
description: > # this means to ignore newlines until "baseurl:"
  We live Wildstar.
baseurl: "/bd-web" # the subpath of your site, e.g. /blog
url: "http://myrealitycoding.github.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

paginate: 2 # pagination basted on number of posts

# Build settings
markdown: kramdown

gems: [ jekyll-paginate ]

exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'bootstrap.scss', 'phpbb', 'classes', 'build.sh', 'buildphp.sh'] # files to exclude

navigation:
- text: Home
  url: /
  icon: fa-home
- text: Über uns
  url: /about/
  icon: fa-flask
- text: Erfolge
  url: /achievements/
  icon: fa-trophy
- text: Forum
  url: /forum/
  icon: fa-comments
- text: Mitglieder
  url: /members/
  icon: fa-user
- text: Live
  url: /live/
  icon: fa-play-circle-o
- text: Medien
  url: /media/
  icon: fa-picture-o

links:
- url: http://www.wildstar-online.com/de/
  name: Wildstar
- url: http://wildstar.gamepedia.com/Wildstar_Wiki
  name: Wiki
- url: /impressum/
  name: Impressum

screenshots:
- src: screenshot01.jpg
  description: Nexus wartet darauf, erobert zu werden!
- src: screenshot03.jpg
  description: Wir warten auf dich. Bewerbe dich jetzt!
- src: screenshot04.jpg
  description: Dieser Planet steckt voller Abenteuer
